
version: "3.8"
services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports: 
      - 4001:3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - WDS_SOCKET_PORT=4002
      - NODE_ENV=production
    ports: 
      - 4002:3000
    restart: unless-stopped

    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      EMAIL: "khaled.abdulhalim.pro@gmail.com"
      REFRESH_TOKEN: "1//04agyJcY7Hk-VCgYIARAAGAQSNwF-L9Irr4zWZeAq2SA3nTb8vL14HlSlGPy3CnjR8G1pRbNCTJTas1t49coRX0N8Hx56xnmkmMM"
      CLIENT_ID: "767730596196-2iqulqj82oa904dm0174ul68v0b209kc.apps.googleusercontent.com"
      CLIENT_SECRET: "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"
      access_token: ya29.A0ARrdaM8nOQK293P_OJJA5uzrSOmKFY-Yek1yRtki5Wn2luykgD5D1cfEfkYVeonBYORqc--w9droV30mYboIDdbzbCHjRHkzdSMkUduK7__w3m-2rchlzIVI34fj8b89yZSl95XxOfJJyFHYUPdmNfhRqWJZYUNnWUtBVEFTQVRBU0ZRRl91NjFWbGtWN0hPWnBuMTkwNERWZW1sYkJTZw0163
      PORT: 4000
      MONGO_URL: "mongodb://root:password@mongo/app"
      DATABASE_URL: "postgres://root:password@db/app"
      SECRET_KEY: RXCT34ZE5GFDSFD756
      NODE_ENV: production
    ports:
      - 4000:4000
      - 9229:9229 
    depends_on:
      - mongo
      - db
    restart: unless-stopped


  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db

  db:
    image: postgres:alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    restart: unless-stopped

volumes: 
  mongo-data: {}
  db-data: {}
 


