version: "3.8"
services:

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    volumes:
      - type: bind
        source: ./admin
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports: 
      - 4001:3000
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - WDS_SOCKET_PORT=4002
    volumes:
      - type: bind
        source: ./client
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports: 
      - 4002:3000
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      EMAIL: "khaled.abdulhalim.pro@gmail.com"
      REFRESH_TOKEN: "1//04gW8NKYuU7WlCgYIARAAGAQSNwF-L9Irb3_5uyOJund2eRivwGtmXtulIZ6odtXTBbhvxcbPazXvAn3Ytkk8HWKUKlUPf2vzS3k"
      CLIENT_ID: "767730596196-9tgosgg878bogpl4a2p38oocmf4cl8mk.apps.googleusercontent.com"
      CLIENT_SECRET: "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"
      access_token: ya29.a0ARrdaM9pt0lavHH_S71y_n3yGzt671rRbIvpv3UEb4uFS34g5pdeMbRyWBYt-kObNgnolNfRlNFrLxt8fo3MBhB1WmPNAMq5u07iOxZIMBOGfMm9UDl36SX00sYBFXZtgKMNIReJZAwxfVCYtHpsJuJWr5v2
      PORT: 4000
      MONGO_URL: "mongodb://root:password@mongo/app"
      DATABASE_URL: "postgres://root:password@db/app"
      SECRET_KEY: RXCT34ZE5GFDSFD756
    volumes:
      - type: bind
        source: ./api/src
        target: /app/src
    ports:
      - 4000:4000
      - 9229:9229 
    depends_on:
      - mongo
      - db
    restart: always

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db

  db:
    image: postgres:alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw



volumes: 
  mongo-data: {}
  db-data: {}
 


  