version: "3.8"
services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./admin
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports: 
      - 4001:3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./client
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports: 
      - 4002:3000
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      PORT: 4000
      MONGO_URL: "mongodb://root:password@mongo/app"
      DATABASE_URL: "postgres://root:password@db/app"
      SECRET_KEY: RXCT34ZE5GFDSFD756
    volumes:
      - type: bind
        source: ./api/src
        target: /app/src
    ports:
      - 4000:4000
      - 9229:9229 
    depends_on:
      - mongo
      - db
    restart: always

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db

  db:
    image: postgres:alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  mariadb:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=taylor
    env_file:
      - ./db.env
    
  app:
    image: matomo
    restart: always
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    ports:
      - 8080:80


volumes: 
  mongo-data: {}
  db-data: {}
  mariadb: 
  matomo: 


  