name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
      - uses: actions/checkout@v2

      - name: Build images
      - run: docker-compose build --no-cache
      
      - name: build containers
      - run: docker-compose up -d

      - name: teste application
      - run: docker-compose exec api npm run test


