name: CI
on:
  push:
    branches: [ "master" ]
jobs:
  build_and_test:
    name: build the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout applicattion
        uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build --no-cache
      - name: build containers
        run: docker-compose up -d
      - name: teste application
        run: docker-compose exec -T api npm run test
  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd utltimatefive && git pull
            docker-compose -f "docker-compose.prod.yml" down --remove-orphans
            docker-compose -f "docker-compose.prod.yml" up -d --build



