name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    name: build the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build --no-cache
      - name: build containers
        run: docker-compose up -d
      - name: teste application
        run: docker-compose exec api npm run test
