name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
      - uses: actions/checkout@v2

      - name: Build images
      - run: docker-compose build --no-cache
      
      - name: build containers
      - run: docker-compose up -d

      - name: teste application
      - run: docker-compose exec api npm run test

  deploy:
  needs: build_and_push
  steps:
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Setup project
    - run: cd utltimatefive

    - name: update version
      run: git pull

    - name: update containers
      run: docker compose -f "docker-compose.yml" up -d --build